M48
; DRILL file {KiCad 8.0.8} date 2025-05-09T18:40:22-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-09T18:40:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.2264
%
G90
G05
T1
X6.1811Y-3.1102
X6.5748Y-3.1102
T2
X6.3976Y-3.3465
M30
